language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
before_script : []

script :
  - docker --version
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed mrnejah/udagram-api-feed:latest
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user mrnejah/udagram-api-user:latest
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend mrnejah/udagram-frontend:latest
  - docker build -t udagram-reverseproxy .
  - docker tag udagram-reverseproxy mrnejah/udagram-reverseproxy:latest

after success :
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mrnejah/udagram-api-feed
  - docker push mrnejah/udagram-api-user
  - docker push mrnejah/udagram-frontend
  - docker push mrnejah/udagram-reverseproxy
